version: "3.9"
services:
  mongodb:
    image: "mongo:latest"
    volumes:
      - ${PWD}/mongodb:/data/db
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
  app:
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${PWD}/app:/app
    ports:
      - "8000:8000"
    container_name: app
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGODB_URL: mongodb://mongodb:27017
  web:
    build:
      context: ./web
      dockerfile: ./docker/Dockerfile
    volumes:
      - ${PWD}/web:/web
    ports:
      - "3000:3000"
    container_name: web
    depends_on:
      - app
    environment:
      WAIT_HOSTS: app:8000
